server:
  port: 8021
  # 开发阶段浏览器不设置缓存，静态资源更新后立马就能访问到
  tomcat:
    processor-cache: 0

servlet:
  context-path: /

spring:
  # Redis配置信息
  data:
    redis:
      host: localhost
      port: 6379 # redis默认端口
      # 默认使用 lettuce，如果使用Jedis需要导入依赖
      lettuce:
        # 连接池配置
        pool:
          max-active: 8
  # Kafka配置信息
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hkbbs-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000 # 自动提交间隔（ms）
  # Tomcat配置信息
  servlet:
    # 启用文件上传
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    # 换数据源（JDBC连接池）
    type: com.alibaba.druid.pool.DruidDataSource
    # 设置连接信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/friends
  # 邮箱配置
  mail:
    default-encoding: utf-8
    # 邮箱主机
    host: smtp.qq.com
    protocol: smtps # smtps 是加了SSL的smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true # 开启SSL

# 腾讯云图床
cos:
  bucket: zhangerfa-1316526930
  region: ap-guangzhou
  path: header/

mybatis:
  # 设置映射文件（mapper.xml）的路径
  mapper-locations: classpath:mapper/*.xml
  # 向pojo对象封装数据的时要扫描的包，这里定义后配置文件中就可以省略包名
  type-aliases-package: site.zhangerfa.pojo
  configuration:
    # 自动完成MySQL中下划线和Java中驼峰命名的转换
    map-underscore-to-camel-case: true
    # 启用属性自增的组件、自增的属性会回填到pojo对象中
    use-generated-keys: true

logging:
  level:
    web: error

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html # swagger-ui的访问路径：http://ip:port/context-path/path
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs # json文档的访问路径
    enabled: true
  group-configs:
    - group: 'hkbbs' # 定义一个文档 group
      # 注释文档包含的包列表
      packages-to-scan: site.zhangerfa.controller
      # 注释文档要包含的路径列表
      paths-to-match: '/**'

knife4j:
  enable: false
  setting:
    language: zh-CN
  basic:
    enable: true